"""mapping for movies index"""
movies_mappings ={
   "properties":{
      "name":{
         "type":"text",
         "analyzer":"english"
      },
      "rating":{
         "type":"text",
         "analyzer":"standard"
      },
      "genre":{
         "type":"text",
         "analyzer":"standard"
      },
      "year":{
         "type":"integer"
      },
      "score":{
         "type":"float"
      },
      "votes":{
         "type":"integer",
      },
      "director":{
         "type":"text",
         "analyzer":"standard"
      },
      "writer":{
         "type":"text",
         "analyzer":"standard"
      },
      "star":{
         "type":"text",
         "analyzer":"standard"
      },
      "country":{
         "type":"text",
         "analyzer":"standard"
      },
      "budget":{
         "type":"integer",
      },
      "gross":{
         "type":"text",
      },
      "company":{
         "type":"text",
         "analyzer":"standard"
      },
      "runtime":{
         "type":"integer",
      }
   }
}